### ISSUE TITLE
error was encountered while requesting a list of devices while interrogating current temperature (TH16)

### ISSUE THREAD

**Issue by minws13** [howanghk/homebridge-ewelink#107]
I get this error, when opening home app and device appears as non-responding. However after scrolling between rooms, or waiting for 30-40 seconds the device appears online. It is kind of strange to have to scroll back and forth to get the device to appear without problems. 

Does anybody have an idea?

[6/19/2020, 10:24:44 PM] [eWeLink] Requesting current humidity for [Device9ea4b1]
[6/19/2020, 10:24:44 PM] [eWeLink] Requesting power state for [Device9ea4b1]
[6/19/2020, 10:24:44 PM] [eWeLink] Requesting current temperature for [Device9ea4b1]
[6/19/2020, 10:24:44 PM] [eWeLink] Requesting current temperature for [Device9ea4b1]
[6/19/2020, 10:24:44 PM] [eWeLink] An error was encountered while requesting a list of devices while interrogating current temperature. Verify your configuration options. Error was [Error: Parsing error : Unexpected token < in JSON at position 0, body= 
 <html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body bgcolor="white">
<center><h1>503 Service Temporarily Unavailable</h1></center>
<hr><center>openresty</center>
</body>
</html>

    at Object.parseBody (/usr/local/lib/node_modules/homebridge-ewelink-max/node_modules/request-json/main.js:67:19)
    at Request._callback (/usr/local/lib/node_modules/homebridge-ewelink-max/node_modules/request-json/main.js:148:26)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-ewelink-max/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-ewelink-max/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-ewelink-max/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1221:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
]
[6/19/2020, 10:24:44 PM] [eWeLink] Sonoff API 503 error
[6/19/2020, 10:24:44 PM] [eWeLink] getCurrentTemperature: 27.5
[6/19/2020, 10:24:44 PM] [eWeLink] setting temperature:  27.5
[6/19/2020, 10:24:44 PM] [eWeLink] setting temperature:  27.5
[6/19/2020, 10:24:44 PM] [eWeLink] getCurrentHumidity: unavailable
[6/19/2020, 10:24:44 PM] [eWeLink] setting humidity:  0
[6/19/2020, 10:24:44 PM] [eWeLink] setting humidity:  0

**Comment by howanghk** [comment]
Hi @minws13, the ewelink server response "503 Service Temporarily Unavailable" means their service is temporarily unavailable. It have nothing to do with this plugin. Are you using a lot of ewelink devices?

**Comment by minws13** [comment]
Hi @howanghk , nope, just 2 devices... and the thing is that I get the error regularly. Well, probably the service is down often. Thanks
