### ISSUE TITLE
Sonoff T1 c2 ch3 and ch4 entries

### ISSUE THREAD

**Issue by Patrik-svobodik** [howanghk/homebridge-ewelink#24]
I get CH3 and CH4 entries for every T1 c2 device I connect, they don’t do anything

**Comment by howanghk** [comment]
Hi @Patrik-svobodik, what is your device model? You can find it on the device settings page in the Home App.

![img_d5d79ff153d4-1](https://user-images.githubusercontent.com/2206845/51432535-618e2380-1c74-11e9-8d87-96c8a3feb82f.jpeg)

**Comment by Patrik-svobodik** [comment]
Are you talking about the CH1 and CH2 or the CH3/CH4?

po 25. 3. 2019 v 11:36 odesílatel Wong Ho Wang <notifications@github.com>
napsal:

**Comment by howanghk** [comment]
any one of them will do.

**Comment by Patrik-svobodik** [comment]
út 26. 3. 2019 v 11:04 odesílatel Wong Ho Wang <notifications@github.com>
napsal:

**Comment by howanghk** [comment]
I do not understand what does that mean except I saw my name in it. I assume that's something injected by your email client? I cannot see the content in your reply. Try replying on GitHub https://github.com/howanghk/homebridge-ewelink/issues/24 instead.

**Comment by Patrik-svobodik** [comment]
Sorry, gmail messed up, here it is:
![A02DD43E-98E1-4989-A90A-449917627D1C](https://user-images.githubusercontent.com/25883885/55084028-cca90b80-50a4-11e9-9eb1-ce588ba4cf39.png)

**Comment by howanghk** [comment]
Hi @Patrik-svobodik, which version of homebridge-ewelink-max were you using? Are you on the latest version (0.1.13 at the time of writing)?

**Comment by Patrik-svobodik** [comment]
Yup

**Comment by howanghk** [comment]
No you're not. Please upgrade it by running

```
sudo npm -g uninstall homebridge-ewelink-max
sudo npm -g install homebridge-ewelink-max
```

**Comment by Patrik-svobodik** [comment]
Ok, will try it, when was it released? I thought I have the newest (and config-x-ui thought as well)

**Comment by howanghk** [comment]
if you are using 0.1.11 or later, there will be a uiid included after the model number. 0.1.11 was released on 21 Jan 2019, more than 2 months ago.
P.S. did you restart homebridge after updating?

**Comment by Patrik-svobodik** [comment]
I did set it up pretty recenly, so yeah, will try updating
čt 28. 3. 2019 v 18:50 odesílatel Wong Ho Wang <notifications@github.com>
napsal:

**Comment by Patrik-svobodik** [comment]
Just checked, I am on 0.1.13

**Comment by howanghk** [comment]
did you restart homebridge after updating?

I need to know the uiid of your device. There should be a number after the model. Like this:

![IMG_0903](https://user-images.githubusercontent.com/2206845/55231531-d88bfd80-525d-11e9-9abf-f8d4633ddc38.PNG)

**Comment by Patrik-svobodik** [comment]
![605AFED3-E7D7-46E5-A899-E02635FC6B0E](https://user-images.githubusercontent.com/25883885/55240577-78836000-5239-11e9-9987-d05384d3335b.png)

**Comment by Patrik-svobodik** [comment]
Sorry, you need the number, some devices have it but some don’t, weird, my lamp for example does, will send another screenshot when I will find it

**Comment by Patrik-svobodik** [comment]
I have found out that none 2 channel devices have the number after the model number, really weird

**Comment by howanghk** [comment]
Oh it seems to be a bug that cause the uiid not always appended. Can you log the content of `platform.devicesFromApi` on [line 118 in index.js](https://github.com/howanghk/homebridge-ewelink/blob/9940ac20224c5e35e0ba8d12af16a4266cc659e5/index.js#L118)?

**Comment by Patrik-svobodik** [comment]
I would happily do so, but I don’t know how 😀

**Comment by haepiyang** [comment]
I'm having this problem right now with the T1 US 3C. It works well only when I control those switches with the Home app. When I turn on/off the switch using the button on the panel it sometimes add another CH 4 switch or throw an error "Cannot add a bridged Accessory with the same UUID as another bridged Accessory" then crash my homebridge. If I toggle the CH4 switch it do crashes my homebridge too.
<img width="1277" alt="Screen Shot 2019-04-29 at 11 18 15" src="https://user-images.githubusercontent.com/20526660/56876337-ddb4b600-6a70-11e9-8530-d986c4e5b7ea.png">

**Comment by hkccmaster** [comment]
> I'm having this problem right now with the T1 US 3C. It works well only when I control those switches with the Home app. When I turn on/off the switch using the button on the panel it sometimes add another CH 4 switch or throw an error "Cannot add a bridged Accessory with the same UUID as another bridged Accessory" then crash my homebridge. If I toggle the CH4 switch it do crashes my homebridge too.
> <img alt="Screen Shot 2019-04-29 at 11 18 15" width="1277" src="https://user-images.githubusercontent.com/20526660/56876337-ddb4b600-6a70-11e9-8530-d986c4e5b7ea.png">

yes, before we press on the physical switch, everything work well. but once it pressed, it will make homekit detect ch3 & ch4 even u are just using a 2 channel wall switch. and it crash with adding ch4 again and again with same uuid.

i know the wall switch with 2 or 3 or 4 channel they are basically the same pcb board with same component, and they are all come with 4 channel physically.

**Comment by haepiyang** [comment]
So do we have any solution for this problem yet?

**Comment by VictorKrasnov** [comment]
1. I have the same problem. Two accessories appear sometimes (about one time at a day). I see in logs and in cashedAccessories file new accessories CH3 & CH4. Homebridge breaks.

```
May 29 08:59:48 homebridge homebridge[15030]: [2019-5-29 08:59:48] [eWeLink] Выключатель кухня CH 1 Configure Accessory
May 29 08:59:48 homebridge homebridge[15030]: [2019-5-29 08:59:48] [eWeLink] Выключатель кухня CH 2 Configure Accessory
May 29 08:59:48 homebridge homebridge[15030]: [2019-5-29 08:59:48] [eWeLink] Выключатель кухня CH 3 Configure Accessory
May 29 08:59:48 homebridge homebridge[15030]: [2019-5-29 08:59:48] [eWeLink] Выключатель кухня CH 4 Configure Accessory
May 29 08:59:48 homebridge homebridge[15030]: [2019-5-29 08:59:48] [eWeLink] Выключатель кухня CH 3 Configure Accessory
May 29 08:59:48 homebridge homebridge[15030]: [2019-5-29 08:59:48] Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 00654204-3786-46a2-8374-a0a35e8433bf
May 29 08:59:48 homebridge homebridge[15030]:     at Bridge.Accessory.addBridgedAccessory (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:268:13)
May 29 08:59:48 homebridge homebridge[15030]:     at Server._configCachedPlatformAccessories (/usr/lib/node_modules/homebridge/lib/server.js:396:18)
May 29 08:59:48 homebridge homebridge[15030]:     at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:93:8)
May 29 08:59:48 homebridge homebridge[15030]:     at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:59:10)
May 29 08:59:48 homebridge homebridge[15030]:     at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
May 29 08:59:48 homebridge homebridge[15030]:     at Module._compile (internal/modules/cjs/loader.js:774:30)
May 29 08:59:48 homebridge homebridge[15030]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
May 29 08:59:48 homebridge homebridge[15030]:     at Module.load (internal/modules/cjs/loader.js:641:32)
May 29 08:59:48 homebridge homebridge[15030]:     at Function.Module._load (internal/modules/cjs/loader.js:556:12)
May 29 08:59:48 homebridge homebridge[15030]:     at Function.Module.runMain (internal/modules/cjs/loader.js:837:10)
May 29 08:59:48 homebridge homebridge[15030]: [2019-5-29 08:59:48] Got SIGTERM, shutting down Homebridge...
May 29 08:59:52 homebridge homebridge[15030]: #033[0;37m[2019-5-29 08:59:52] #033[0m#033[0;36m[Config]#033[0m #033[0;33mConsole v4.4.2 is listening on :: port 8080#033[0m
May 29 08:59:53 homebridge systemd[1]: homebridge.service: Main process exited, code=exited, status=143/n/a
May 29 08:59:53 homebridge systemd[1]: homebridge.service: Unit entered failed state.
May 29 08:59:53 homebridge systemd[1]: homebridge.service: Failed with result 'exit-code'.
May 29 08:59:58 homebridge systemd[1]: homebridge.service: Service hold-off time over, scheduling restart.
May 29 08:59:58 homebridge systemd[1]: Stopped Node.js HomeKit Server.
May 29 08:59:58 homebridge systemd[1]: Started Node.js HomeKit Server.
```
2. Automatisation (like turn on/off all switches) with Sonoff T1 2 gangs doesn't work in 50% cases. In that case one of lamp doesn't switch, but Home.app shows that it done.

**Comment by VictorKrasnov** [comment]
My fix  for this bug: https://www.npmjs.com/package/homebridge-ewelink-krasnov
Or see this commit: https://github.com/VictorKrasnov/homebridge-ewelink/commit/05a722ef42d0ed7d1a065615ac12d39d92ddda70

**Comment by howanghk** [comment]
@VictorKrasnov Thanks! I have merged your fix and published a new version 0.1.15 on npm.

**Comment by howanghk** [comment]
Hi all, there is another multi-channel fix by jacopofranza in https://github.com/howanghk/homebridge-ewelink/pull/86 , please install the latest version 0.1.21 and try again.

```
npm install -g homebridge-ewelink-max@latest
```

You may also need to clear existing accessories cache (remove the `accessories` directory in homebridge folder).

**Comment by RashmiMendis** [comment]
@howanghk Hi is this supports SONOFF T3 3Gang version?

**Comment by rashmendis** [comment]
@howanghk Hi is this supports SONOFF T3 3Gang version?
