### ISSUE TITLE
"error":401,"info":"user is null in local"

### ISSUE THREAD

**Issue by rob0101** [howanghk/homebridge-ewelink#31]
I can't get past this error.

[eWeLink] Server did not response with an authentication token. Response was [{"error":401,"info":"user is null in local"}]

Running on a raspberry pi.

Anyone able to help ?

Trying to get a couple of wifi smart sockets working.
Both controllable in the iPhone app.
Tried logging out of the app.
Tried changing the app version number to match the phone (3.6.1).

thanks

**Comment by howanghk** [comment]
Hi @rob0101, most probably your config is incorrect.

**Comment by rob0101** [comment]
here's my config

{
            "platform" : "eWeLink",
            "name" : "eWeLink",
            "email" : "my@email.address",
            "password" : "mypassword",
            "imei" : "ED532BB2-7C1B-4C17-BCAA-1B149C2ECD91"
        },

**Comment by sschnoor** [comment]
FWIW exact same issue for me.  Same config as rob0101.

{
"platform" : "eWeLink",
"name" : "eWeLink",
"email" : "my@email.address",
"password" : "mypassword",
"imei" : "ED532BB2-7C1B-4C17-BCAA-1B149C2ECD91"
},

Any thoughts?

**Comment by howanghk** [comment]
Hi @rob0101 and @sschnoor, where are you guys from? Try adding 
```
"apiHost": "eu-api.coolkit.cc:8080",
```
to the config and see if it make any different?

**Comment by rob0101** [comment]
@howanghk 
I'm in Australia. Just tried eu, au, as, cn and all produce the same error.

Thanks for your assistance.

**Comment by rob0101** [comment]
With cn-long I get a different issue:

[15/06/2019, 2:03:29 pm] TypeError: Cannot read property 'hasOwnProperty' of undefined
    at eWeLink.<anonymous> (/usr/local/lib/node_modules/homebridge-ewelink-max/index.js:987:18)
    at Object.parseBody (/usr/local/lib/node_modules/homebridge-ewelink-max/node_modules/request-json/main.js:74:12)
    at Request._callback (/usr/local/lib/node_modules/homebridge-ewelink-max/node_modules/request-json/main.js:148:26)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-ewelink-max/node_modules/request-json/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-ewelink-max/node_modules/request-json/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-ewelink-max/node_modules/request-json/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by rob0101** [comment]
Apologies. I found my error. It was a typo in the password.

Working here now.
Thanks.

**Comment by sschnoor** [comment]
I’m US.  So us-api.... ?

**Comment by howanghk** [comment]
Thanks for confirming "user is null in local" means authentication error. I am closing this issue now.
