### ISSUE TITLE
Cannot read property 'pollerperiod' error

### ISSUE THREAD

**Issue by rustymh** [howanghk/homebridge-ewelink#45]
Why is it giving me pollerperiod error? Even if I do add pollerperiod with value in as "0" or "1", it still complain. My config is as per example.

`
Load homebridge-blynk.Blynk
[9/3/2019, 8:14:10 AM] TypeError: Cannot read property 'pollerperiod' of null
    at new Blynk (/usr/lib/node_modules/homebridge-blynk/dist/index.js:72:40)
    at Server._loadDynamicPlatforms (/usr/lib/node_modules/homebridge/lib/server.js:358:30)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:92:8)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
`

**Comment by rustymh** [comment]
Issue point to the blynk plugin. Seems like ewelink and blynk has an issue working together. I can run blynk successfully on its own.

**Comment by howanghk** [comment]
Hi @rustymh, as you have pointed out, the error is entirely on homebridge-blynk side, which have nothing to do with homebridge-ewelink-max. The homebridge plugin platform ensure each plugin works on its own and won't affect the others.
