### ISSUE TITLE
Error: Attempting to register a platform 'homebridge-eWeLink.eWeLink' which has already been registered!

### ISSUE THREAD

**Issue by arno93** [howanghk/homebridge-ewelink#53]
hi,

i am Arnaud From France

i am new on Homebridge/ Debian ...etc
I did install Homebridge on a VM and tried to install also ewe link plugin, 
i edit my config.json but I have trouble when I try to launch HOMEBRIDGE

here is the complete error message

root@debian:/home/freebox# homebridge
[10/22/2019, 11:48:57 AM] Loaded config.json with 0 accessories and 1 platforms.
[10/22/2019, 11:48:57 AM] ---
[10/22/2019, 11:48:58 AM] Loaded plugin: homebridge-ewelink
homebridge API version: 2.4
[10/22/2019, 11:48:58 AM] Registering platform 'homebridge-eWeLink.eWeLink'
[10/22/2019, 11:48:58 AM] ---
[10/22/2019, 11:48:58 AM] Loaded plugin: homebridge-ewelink-max
homebridge API version: 2.4
/usr/lib/node_modules/homebridge/lib/api.js:150
    throw new Error("Attempting to register a platform '" + fullName + "' which has already been registered!");
    ^

Error: Attempting to register a platform 'homebridge-eWeLink.eWeLink' which has already been registered!
    at API.registerPlatform (/usr/lib/node_modules/homebridge/lib/api.js:150:11)
    at Plugin.module.exports [as initializer] (/usr/lib/node_modules/homebridge-ewelink-max/index.js:30:16)
    at Server.<anonymous> (/usr/lib/node_modules/homebridge/lib/server.js:171:14)
    at Array.forEach (<anonymous>)
    at Server._loadPlugins (/usr/lib/node_modules/homebridge/lib/server.js:145:22)
    at new Server (/usr/lib/node_modules/homebridge/lib/server.js:57:24)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:32:16)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:945:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:962:10)

thanks a lot for your support

**Comment by howanghk** [comment]
Hi @arno93, it seems you have multiple ewelink plugin installed. Please uninstall other ewelink plugin (such as homebridge-ewelink and homebridge-ewelink-plus) and try again:

```
npm uninstall -g homebridge-ewelink homebridge-ewelink-plus
```

**Comment by howanghk** [comment]
Closing due to inactivity.
