### ISSUE TITLE
503 Service Temporarily Unavailable

### ISSUE THREAD

**Issue by imsturmdernacht** [howanghk/homebridge-ewelink#59]
Dear people,

I got the following errors since yesterday evening. Is it a problem of my configuration or is it a problem on ewelink servers?

Regards

[2019-11-14 13:40:50] [eWeLink] An error was encountered while requesting a list of devices while interrogating power status. Error was [Error: Parsing error : Unexpected token < in JSON at position 0, body=
 <html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body bgcolor="white">
<center><h1>503 Service Temporarily Unavailable</h1></center>
<hr><center>openresty</center>
</body>
</html>
]
[2019-11-14 13:40:50] [eWeLink] An error was encountered while requesting a list of devices while interrogating power status. Error was [Error: Parsing error : Unexpected token < in JSON at position 0, body=
 <html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body bgcolor="white">
<center><h1>503 Service Temporarily Unavailable</h1></center>
<hr><center>openresty</center>
</body>
</html>
]
[2019-11-14 13:40:50] [eWeLink] An error was encountered while requesting a list of devices while interrogating power status. Error was [Error: Parsing error : Unexpected token < in JSON at position 0, body=
 <html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body bgcolor="white">
<center><h1>503 Service Temporarily Unavailable</h1></center>
<hr><center>openresty</center>
</body>
</html>
]

**Comment by urmo53** [comment]
i have same problem too

**Comment by howanghk** [comment]
Does the official eWeLink works for you?

**Comment by imsturmdernacht** [comment]
I‘ve tested different ewelink plugins and also the original Homebridge-ewelink, it‘s always the same. The Ewelink iOS App is working fine.

**Comment by urmo53** [comment]
ewelink app works, strange that even if i give commands to Siri they work, but the home app shows no response ok switches. And homebridge shows same error 503 Service.......

**Comment by imsturmdernacht** [comment]
Exactly the same behavior on my homebridge.

**Comment by imsturmdernacht** [comment]
More detailed Error information:

[2019-11-15 10:55:04] [eWeLink] An error was encountered while requesting a list of devices while interrogating power status. Error was [Error: Parsing error : Unexpected token < in JSON at position 0, body=
 <html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body bgcolor="white">
<center><h1>503 Service Temporarily Unavailable</h1></center>
<hr><center>openresty</center>
</body>
</html>
    at Object.parseBody (/usr/local/lib/node_modules/homebridge-ewelink-max/node_modules/request-json/main.js:67:19)
    at Request._callback (/usr/local/lib/node_modules/homebridge-ewelink-max/node_modules/request-json/main.js:148:26)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-ewelink-max/node_modules/request/request.js:185:22)
    at Request.emit (events.js:210:5)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-ewelink-max/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:210:5)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-ewelink-max/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:299:28)
    at IncomingMessage.emit (events.js:215:7)
    at endReadableNT (_stream_readable.js:1183:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)]

**Comment by pdonat01** [comment]
Same problem here with sonoff s20 ac official firmware

**Comment by pavoroby** [comment]
Did you find a solution?

**Comment by pdonat01** [comment]
No,
But a little bit strange. I have sonoff tx swich and s20 ac adapter. If i delete the s20 ac adapter the plugin working fine. Maybe the ac plug type devices cause the error.

**Comment by imsturmdernacht** [comment]
In my case there are 7 Sonoff Touch EUC1 and one T1 1C. Problem exists since last Thursday evening without any changes on the whole setup. No solution so far. Homebridge shows no response on all devices.

**Comment by pdonat01** [comment]
Yes the problem appear from last thursday. Then the problem is on ewelink side :/
The developer know any solution?

**Comment by imsturmdernacht** [comment]
503 means for me a server or a service is no longer responding. But I don‘t know which one or how to replace or correct it.

**Comment by tanini23** [comment]
Same problem here. Does anybody knows how to fix it?

**Comment by imsturmdernacht** [comment]
Nothing new so far.. plugin still not working, my homebridge is down

**Comment by tawagny** [comment]
same problem here ..
 at Object.parseBody (/usr/local/lib/node_modules/homebridge-ewelink-max/node_modules/request-json/main.js:67:19)
    at Request._callback (/usr/local/lib/node_modules/homebridge-ewelink-max/node_modules/request-json/main.js:148:26)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-ewelink-max/node_modules/request/request.js:185:22)
    at Request.emit (events.js:210:5)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-ewelink-max/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:210:5)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-ewelink-max/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:299:28)
    at IncomingMessage.emit (events.js:215:7)
    at endReadableNT (_stream_readable.js:1183:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)

**Comment by pavoroby** [comment]
I had to abandon this plugin.  I switched to homeassistant and a solution with lan mode.
https://github.com/AlexxIT/SonoffLAN (Russian lang in readme)

**Comment by tawagny** [comment]
> I had to abandon this plugin. I switched to homeassistant and a solution with lan mode.
> https://github.com/AlexxIT/SonoffLAN (Russian lang in readme)

any pointers on how to migrate is appreciated

**Comment by urmo53** [comment]
I reset 5 of my 11 devices I use the most and shared them with my second ewelink user.
i replaced this ewelikn plugin with it https://github.com/VictorKrasnov/homebridge-ewelink
at the moment they haven't had more problems with at least their 5, at least the first 12h

**Comment by tawagny** [comment]
thank you .. will give it a try

**Comment by tawagny** [comment]
@urmo53  Thanks that seemed to resolve the issue

**Comment by howanghk** [comment]
The fix from VictorKrasnov have been incorporated in the latest version. Please install the latest version with

```
npm install -g homebridge-ewelink-max@latest
```
